// Generated by tools/ringtone-gen/generate_ringtones.py - do not edit by hand.
//
// Re-run the generator to regenerate both the audio files and this catalogue,
// so the two can never drift apart:
//
//     python tools/ringtone-gen/generate_ringtones.py \
//         --out core/audio/src/main/res/raw \
//         --kotlin-out core/audio/src/main/kotlin/io/github/ruiquanqiao/alarmsets/core/audio/BundledRingtones.kt

package io.github.ruiquanqiao.alarmsets.core.audio

import io.github.ruiquanqiao.alarmsets.core.model.RingtoneCategory

/** A tone shipped inside the APK, addressed by [key] and stored in `res/raw`. */
data class BundledRingtone(
    val key: String,
    val title: String,
    val description: String,
    val category: RingtoneCategory,
    val durationMillis: Long,
)

object BundledRingtones {

    val ALL: List<BundledRingtone> = listOf(
        BundledRingtone(
            key = "dawn_chime",
            title = "Dawn Chime",
            description = "Soft bell arpeggio that rises and settles.",
            category = RingtoneCategory.GENERAL,
            durationMillis = 4600L,
        ),
        BundledRingtone(
            key = "marimba",
            title = "Marimba",
            description = "Warm wooden mallet pattern.",
            category = RingtoneCategory.GENERAL,
            durationMillis = 3000L,
        ),
        BundledRingtone(
            key = "harp_rise",
            title = "Harp Rise",
            description = "Plucked ascending run.",
            category = RingtoneCategory.GENERAL,
            durationMillis = 3600L,
        ),
        BundledRingtone(
            key = "digital_pulse",
            title = "Digital Pulse",
            description = "Classic triple-beep alarm.",
            category = RingtoneCategory.GENERAL,
            durationMillis = 3200L,
        ),
        BundledRingtone(
            key = "radar",
            title = "Radar",
            description = "Two-tone pulse that grows louder.",
            category = RingtoneCategory.GENERAL,
            durationMillis = 4000L,
        ),
        BundledRingtone(
            key = "vibraphone",
            title = "Vibraphone",
            description = "Sustained chords with slow tremolo.",
            category = RingtoneCategory.GENERAL,
            durationMillis = 4400L,
        ),
        BundledRingtone(
            key = "music_box",
            title = "Music Box",
            description = "Delicate plucked melody.",
            category = RingtoneCategory.GENERAL,
            durationMillis = 3400L,
        ),
        BundledRingtone(
            key = "bell_tower",
            title = "Bell Tower",
            description = "Deep bronze bell struck three times.",
            category = RingtoneCategory.GENERAL,
            durationMillis = 6000L,
        ),
        BundledRingtone(
            key = "beacon",
            title = "Beacon",
            description = "Insistent alternating two-tone.",
            category = RingtoneCategory.GENERAL,
            durationMillis = 3600L,
        ),
        BundledRingtone(
            key = "sonar",
            title = "Sonar",
            description = "Low ping with a long tail.",
            category = RingtoneCategory.GENERAL,
            durationMillis = 5000L,
        ),
        BundledRingtone(
            key = "twin_bell_long",
            title = "Twin Bell Clock (Long)",
            description = "Wind-up alarm clock. The old-fashioned ding-ling-ling-ling.",
            category = RingtoneCategory.SCHOOL,
            durationMillis = 4500L,
        ),
        BundledRingtone(
            key = "twin_bell_short",
            title = "Twin Bell Clock (Short)",
            description = "Short rattle. Warning bell before a period starts.",
            category = RingtoneCategory.SCHOOL,
            durationMillis = 1500L,
        ),
        BundledRingtone(
            key = "twin_bell_urgent",
            title = "Twin Bell Clock (Urgent)",
            description = "Faster and brighter. Hard to sleep through.",
            category = RingtoneCategory.SCHOOL,
            durationMillis = 4000L,
        ),
        BundledRingtone(
            key = "electric_bell_long",
            title = "Electric Bell (Long)",
            description = "The classic corridor bell. Deeper than the wind-up clock.",
            category = RingtoneCategory.SCHOOL,
            durationMillis = 4500L,
        ),
        BundledRingtone(
            key = "electric_bell_short",
            title = "Electric Bell (Short)",
            description = "Short burst of the corridor bell.",
            category = RingtoneCategory.SCHOOL,
            durationMillis = 1300L,
        ),
        BundledRingtone(
            key = "fur_elise",
            title = "Fur Elise",
            description = "Beethoven, 1810. A common end-of-period tune.",
            category = RingtoneCategory.SCHOOL,
            durationMillis = 5400L,
        ),
        BundledRingtone(
            key = "ode_to_joy",
            title = "Ode to Joy",
            description = "Beethoven, 1824.",
            category = RingtoneCategory.SCHOOL,
            durationMillis = 6000L,
        ),
        BundledRingtone(
            key = "greensleeves",
            title = "Greensleeves",
            description = "Traditional English, printed 1580.",
            category = RingtoneCategory.SCHOOL,
            durationMillis = 8000L,
        ),
        BundledRingtone(
            key = "canon",
            title = "Canon in D",
            description = "Pachelbel, around 1680.",
            category = RingtoneCategory.SCHOOL,
            durationMillis = 7600L,
        ),
        BundledRingtone(
            key = "class_begin",
            title = "Class Begin",
            description = "Descending chime. Time to settle down.",
            category = RingtoneCategory.SCHOOL,
            durationMillis = 3800L,
        ),
        BundledRingtone(
            key = "class_end",
            title = "Class End",
            description = "Ascending chime. Period over.",
            category = RingtoneCategory.SCHOOL,
            durationMillis = 3800L,
        ),
        BundledRingtone(
            key = "westminster_full",
            title = "Westminster Chime (Full)",
            description = "The full four-phrase hour chime.",
            category = RingtoneCategory.SCHOOL,
            durationMillis = 12600L,
        ),
        BundledRingtone(
            key = "westminster_quarter",
            title = "Westminster Chime (Quarter)",
            description = "Single phrase. Marks the quarter hour.",
            category = RingtoneCategory.SCHOOL,
            durationMillis = 5100L,
        ),
        BundledRingtone(
            key = "bamboo_chime",
            title = "Bamboo Chime",
            description = "Lyrical pentatonic melody.",
            category = RingtoneCategory.SCHOOL,
            durationMillis = 4800L,
        ),
        BundledRingtone(
            key = "school_chime",
            title = "School Chime",
            description = "Two-tone announcement chime.",
            category = RingtoneCategory.SCHOOL,
            durationMillis = 3400L,
        ),
    )

    private val byKey: Map<String, BundledRingtone> = ALL.associateBy { it.key }

    fun find(key: String): BundledRingtone? = byKey[key]

    fun of(category: RingtoneCategory): List<BundledRingtone> =
        ALL.filter { it.category == category }
}
